# Generated by Django 6.0 on 2025-12-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_agent_branch_agent_cuil_agent_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
