# Generated by Django 5.1.4 on 2025-12-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_agent_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='cuil',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='dni',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
