# Generated by Django 5.1.4 on 2025-12-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_agent_cuil_alter_agent_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='dni',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
