# Generated by Django 5.1.4 on 2025-12-14 00:57

from django.db import migrations, models



def cleanup_duplicates(apps, schema_editor):
    # Delete all agents to allow unique constraint application
    Agent = apps.get_model('api', 'Agent')
    Agent.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_agent_cuil_alter_agent_dni_and_more'),
    ]

    operations = [
        migrations.RunPython(cleanup_duplicates),
        migrations.AlterField(
            model_name='agent',
            name='dni',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
